version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./back/environments/db.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql:cached
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build: back/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && (bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    env_file:
      - ./back/environments/db.env
    environment:
      RAILS_ENV: development
      NODE_ENV: development
    volumes:
      - ./back:/app:cached
      - bundle-cache:/app/vendor/bundle
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3000:3000

  front:
    build: front/
    command: /bin/sh -c "yarn install --frozen-lockfile && yarn dev"
    volumes:
      - ./front:/app:cached
      - front-node-modules:/app/node_modules
    ports:
      - 8080:3000
    depends_on:
      - back
    restart: unless-stopped
volumes:
  db-data:
  bundle-cache:
  front-node-modules:
